# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.reshape(arr, (2,5), order='C')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([5, 6, 7, 8, 9])
z=np.array([1,1,1,1,1])
np.vstack((x,y,z,z))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [8]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([5, 6, 7, 8, 9])
z=np.array([1,1,1,1,1])
np.vstack((np.hstack((x,z)),np.hstack((y,z))))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [10]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9]])
arr.reshape(-1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [11]:
arr = np.array([[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14]])
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [14]:
arr=np.arange(25).reshape((5,5))
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [15]:
arr=np.arange(30).reshape((5,6))
np.mean(arr)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [16]:
np.std(arr)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [17]:
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [18]:
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [24]:
arr=np.array([[5,9,7,23],[6,9,2,17],[55,5,7,3],[4,11,81,46]])
np.trace(arr)

67

## Question:13

### Find the determinant of the previous array in Q12?

In [25]:
np.linalg.det(arr)

156662.00000000026

## Question:14

### Find the 5th and 95th percentile of an array?

In [27]:
arr=np.array([56,78,23,94,56,67,42,85,58,86,45])
np.percentile(arr,5)
np.percentile(arr,95)


90.0

## Question:15

### How to find if a given array has any null values?

In [28]:
np.isnan(arr)

array([False, False, False, False, False, False, False, False, False,
       False, False])